const assert=require('node:assert/strict');
const fs=require('node:fs');
const html=fs.readFileSync(__dirname+'/report-gudang.html','utf8');
assert(html.includes('report-gudang-build-v74-local-first-cache74'),'v74 local-first marker missing');
assert(/\.cover-hero\{[\s\S]{0,280}width:69%[\s\S]{0,300}clip-path:polygon\(35% 0/.test(html),'reference-style diagonal photo panel missing');
assert(/\.cover-slide:before\{[\s\S]{0,360}linear-gradient\(135deg/.test(html),'soft diagonal white overlay missing');
assert(/\.cover-slide:after\{[\s\S]{0,360}radial-gradient/.test(html),'teal lower-right glow missing');
assert(html.includes('-webkit-background-clip:text'),'teal gradient title missing');
assert(html.includes('.cover-icon svg{width:52px;height:52px'),'outline cover icons missing');
console.log('Reference-style lighting cover layout passed');
