const assert=require('node:assert/strict');
const cover=require('./report-gudang-cover');
const master=require('./report-gudang-master');
const sections=master.normalizeSections({},cover.defaultCover());
const lighting=sections['gudang-lighting'].cover;
assert.equal(lighting.brandLine1,'RENTAL');
assert.equal(lighting.brandLine2,'MULTIMEDIA');
assert.equal(lighting.brandLine3,'EVENT SOLUTION');
assert.equal(lighting.titleTop1,'// LAPORAN GUDANG');
assert.equal(lighting.titleTop2,'// REPORT LIGHTING');
assert.equal(lighting.dataPrefix,'DATA :');
assert.equal(lighting.item1,'SERVICE');
assert.equal(lighting.item2,'BARANG KURANG');
assert.equal(lighting.item3,'KOMPLAIN');
assert.equal(lighting.image,'/report-cover-gudang-lighting.jpg');
const migrated=master.normalizeSections({'gudang-lighting':{cover:{titleTop1:'// PT BLUE STAR MEDIA',titleTop2:'// GUDANG LIGHTING',dataPrefix:'REPORT :',item1:'RINGKASAN',item2:'KENDALA',item3:'TINDAK LANJUT',footerRight:'// GUDANG LIGHTING'},slides:[]}},cover.defaultCover())['gudang-lighting'].cover;
assert.equal(migrated.titleTop1,'// LAPORAN GUDANG');
assert.equal(migrated.titleTop2,'// REPORT LIGHTING');
assert.equal(migrated.dataPrefix,'DATA :');
assert.equal(migrated.item1,'SERVICE');
assert.equal(migrated.item2,'BARANG KURANG');
assert.equal(migrated.item3,'KOMPLAIN');
const custom=master.normalizeSections({'gudang-lighting':{cover:{titleTop1:'CUSTOM TOP',item1:'CUSTOM ITEM'},slides:[]}},cover.defaultCover())['gudang-lighting'].cover;
assert.equal(custom.titleTop1,'CUSTOM TOP');
assert.equal(custom.item1,'CUSTOM ITEM');
console.log('Lighting reference cover defaults and safe migration passed');
