const assert=require('node:assert/strict');
const fs=require('node:fs');
const vm=require('node:vm');
const api=require('./report-it-products');
const context={window:{}};
vm.runInNewContext(fs.readFileSync(__dirname+'/report-it-products-data.js','utf8'),context);
const source=JSON.parse(JSON.stringify(context.window.BSMITProductData));
assert.equal(source.length,462);
const rows=[['Analisis Produk'],['No','Nama Produk','Januari','Februari','Maret','April','Mei','Juni','Jan→Feb %','Status Juni']];
source.forEach(p=>rows.push([p.no,p.name,...p.values.slice(0,6),0.5,'NAIK']));
const parsed=api.parseWorkbook({SheetNames:['Analisis Produk'],Sheets:{'Analisis Produk':rows}},{utils:{sheet_to_json:s=>s}});
assert.deepEqual(parsed.map(p=>[p.name,p.values]),source.map(p=>[p.name,p.values]));
const slides=api.createSlides(parsed);
assert.equal(slides.length,29);
assert.equal(slides.at(-1).products.length,14);
assert.equal(slides.flatMap(s=>s.products).length,462);
assert.deepEqual(slides[0].hiddenMonths,[]);
assert.equal(parsed[0].values[5],219575000);
assert.equal(parsed[0].values[6],null);
const juneHtml=api.renderSlide(slides[0]);
assert(juneHtml.includes('<th>Jun</th>'));
assert(!juneHtml.includes('<th>Jul</th>'));
assert(!juneHtml.includes('<th>Des</th>'));
assert(juneHtml.includes('vs Jan'));
assert(juneHtml.includes('vs Mei'));
const extended=api.parseRows([['Nama Produk','Des','Jul','Jan','Jan→Feb %'],['<script>"', 'Rp1.250.000',0,'',99]]);
assert.equal(extended[0].values[11],1250000);
assert.equal(extended[0].values[6],0);
assert.equal(extended[0].values[0],null);
assert(!api.renderSlide(api.createSlides(extended)[0]).includes('<script>'));
assert(!api.renderSlide(api.createSlides([{name:'Zero',values:Array(12).fill(0)}])[0]).includes('NaN'));
assert.equal(api.growth(100,125).status,'NAIK');
assert.equal(api.growth(0,125).status,'BARU');
assert.equal(api.growth(100,null).status,'');
const hiddenSlide=api.createSlides([{name:'A',values:[100,125,150,null,null,null,null,null,null,null,null,null]}])[0];
hiddenSlide.hiddenMonths=[1];
const hiddenHtml=api.renderSlide(hiddenSlide);
assert(hiddenHtml.includes('<th>Jan</th>'));
assert(!hiddenHtml.includes('<th>Feb</th>'));
assert(hiddenHtml.includes('<th>Mar</th>'));
assert(hiddenHtml.includes('Status Mar'));
assert.throws(()=>api.parseRows([['Nama Produk','Jan'],['A','invalid']]));
assert.throws(()=>api.parseRows([['Nama Produk','Jan','Januari'],['A',1,2]]));
console.log('IT workbook: 462 products, 29 slides, month-to-month comparisons, hidden columns, blanks and escaping passed');
