const {chromium}=require('playwright');const fs=require('fs'),http=require('http'),assert=require('assert');
const base=require('path').resolve(__dirname,'..');
const luminance=s=>s.match(/\d+/g).slice(0,3).map(Number).map(v=>v/255).map(v=>v<=.04045?v/12.92:((v+.055)/1.055)**2.4).reduce((a,v,i)=>a+v*[.2126,.7152,.0722][i],0);
const contrast=(a,b)=>{a=luminance(a);b=luminance(b);return (Math.max(a,b)+.05)/(Math.min(a,b)+.05)};
const fixture={general:{siteName:'Fixture Camera'},customProducts:[{id:'keep-product',name:'Camera Fixture',price:250000,stock:2,images:['https://example.com/one.jpg','https://example.com/two.jpg']}],appearance:{},footer:{description:'Original description',copyright:'Original copyright',columns:[]}};
let reviewRows=[{id:'test-review',name:'Pelanggan Uji',kind:'review',rating:4,message:'Layanan rental sangat baik.',published:false,created_at:'2026-10-02T00:00:00Z'},{id:'test-feedback',name:'Masukan Uji',kind:'feedback',message:'Tambahkan pilihan peralatan.',published:false,created_at:'2026-10-02T00:00:00Z'}];
let saved=structuredClone(fixture),writes=0,failSave=false;
const server=http.createServer((req,res)=>{
 if(req.url.startsWith('/produk/')){res.setHeader('Content-Type','text/html');return res.end(`<html><head><link rel="stylesheet" href="/product-knowledge-20261002.css"></head><body><main id="app"></main><script>window.P=[];window.RENTCAM_CMS_CONFIG={};function render(){document.getElementById('app').innerHTML='<h1>'+String(P[0]?.name||'Product')+'</h1>'}</script><script src="/product-knowledge-20261002.js"></script><script src="/seo-runtime-20260930.js"></script><script src="/product-preview-20261002.js"></script></body></html>`);}
 if(req.url==='/cms'){res.setHeader('Content-Type','text/html');return res.end(`<!doctype html><html><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><link rel="stylesheet" href="/cms-v5-readable-20260912.css"><link rel="stylesheet" href="/cms-appearance-20260930.css"></head><body><main id="app"></main><script>localStorage.setItem('rentcam_cms_auth',JSON.stringify({access_token:'local-test-only'}));window.P=[{id:"website-camera",name:"Website Camera",brand:"Fixture Brand",cat:"Camera",price:100000,img:"https://example.com/camera.jpg"}];window.SL=[{id:"website-promo",t:"Website Promo",p:"Original promo",img:"https://example.com/banner.jpg"}];window.PORT=[];window.ART=[];</script><script src="/website-design-lib-20260930.js"></script><script src="/cms-config-store-20260918.js"></script><script src="/cms-publishing-20260918.js"></script><script src="/cms-admin-all-tables-adapter-20260918.js"></script><script src="/cms-ui-final-20260918.js"></script><script src="/cms-template-publishing-adapter-20260918.js"></script></body></html>`);}
 const file=base+req.url;if(!file.startsWith(base+'/')||req.url.includes('..')){res.statusCode=404;return res.end();}
 try{res.setHeader('Content-Type',req.url.endsWith('.css')?'text/css':'application/javascript');res.end(fs.readFileSync(file));}catch(_){res.statusCode=404;res.end();}
});
(async()=>{
 await new Promise(r=>server.listen(0,'127.0.0.1',r));const url='http://127.0.0.1:'+server.address().port+'/cms';
 const browser=await chromium.launch({headless:true,executablePath:'/usr/bin/chromium',args:['--no-sandbox']});
 const context=await browser.newContext();
 await context.route('https://xleceiffuopioeguniwj.supabase.co/**',async route=>{
  const req=route.request();if(req.url().includes('/rest/v1/rentcam_reviews')){if(req.method()==='PATCH'){reviewRows[0].published=JSON.parse(req.postData()).published;return route.fulfill({status:204})}return route.fulfill({contentType:'application/json',body:JSON.stringify(reviewRows)})}if(req.url().includes('/rest/v1/rentcam_order_catalog'))return route.fulfill({contentType:'application/json',body:'[]'});if(!req.url().includes('/rest/v1/rentcam_cms_config'))throw Error('Unexpected network request: '+req.url());
  if(req.method()==='PATCH'){if(failSave)return route.fulfill({status:500,contentType:'application/json',body:JSON.stringify({message:'Fixture save error'})});saved=JSON.parse(req.postData()).config;writes++;return route.fulfill({status:204});}
  return route.fulfill({contentType:'application/json',body:JSON.stringify([{config:saved}])});
 });
 const page=await context.newPage();const errors=[];page.on('pageerror',e=>errors.push(e.message));
 await page.goto(url);await page.locator('[data-field="theme.switchEnabled"]').waitFor();assert.equal(await page.locator('.v5-nav').evaluate(e=>e.firstElementChild.className),'v5-design-menu');assert.equal(await page.locator('.v5-design-menu summary').textContent(),'Pengaturan Web');
 assert.equal(await page.locator('.v5-design-menu').count(),1);assert.equal(await page.locator('.v5-design-menu [data-tpl-nav]').count(),1);
 await page.locator('[data-nav=reviews]').click();await page.locator('[data-review-publish]').waitFor();assert.equal(await page.locator('[data-review-publish]').count(),1);await page.locator('[data-review-publish]').click();await page.getByRole('button',{name:'Sembunyikan',exact:true}).waitFor();assert.equal(reviewRows[0].published,true);await page.getByRole('button',{name:'Sembunyikan',exact:true}).click();await page.getByRole('button',{name:'Tampilkan di Website',exact:true}).waitFor();assert.equal(reviewRows[0].published,false);await page.locator('[data-nav=design-features]').click();
 for(const width of [1440,390,320]){
  await page.setViewportSize({width,height:900});await page.screenshot({path:require('path').join(require('os').tmpdir(),'cms-workspace-'+width+'.png')});
  assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth),width);
 }
 await page.setViewportSize({width:1440,height:1000});
 for(const mode of ['black','white']){if(await page.evaluate(()=>document.documentElement.dataset.cmsTheme)!==mode)await page.locator('[data-act="cms-theme"]').click();assert.equal(await page.evaluate(()=>document.documentElement.dataset.cmsTheme),mode);const colors=await page.locator('.v5-card').first().evaluate(e=>({bg:getComputedStyle(e).backgroundColor,text:getComputedStyle(e).color}));assert.ok(contrast(colors.bg,colors.text)>=4.5);const note=await page.locator('.v5-design-note').evaluate(e=>({bg:getComputedStyle(e).backgroundColor,text:getComputedStyle(e).color}));assert.ok(contrast(note.bg,note.text)>=4.5,'Note contrast in '+mode);}
 const required=['products','masters','banners','portfolio','articles','services','home','media','site','footer','analytics','search','data','design-nav','design-theme'];for(const key of required)assert.equal(await page.locator('.v5-design-menu [data-nav="'+key+'"]').count(),1,key);
 assert.equal(await page.locator('.v5-design-menu [data-tpl-nav]').count(),1);
 await page.evaluate(()=>{const b=document.createElement('button');b.dataset.rentalNav='rentals';b.textContent='Rental';document.querySelector('.v5-nav').append(b);});await page.addScriptTag({url:'/rental-professional-adapter-20260918.js'});await page.waitForTimeout(300);assert.equal(await page.locator('.v5-nav').evaluate(n=>n.firstElementChild.className),'v5-design-menu');for(const key of required)assert.equal(await page.locator('.v5-design-menu [data-nav="'+key+'"]').count(),1,key);
 await page.locator('.v5-design-links [data-nav="design-theme"]').click();await page.locator('[data-field="theme.accent"]').fill('#1266cc');await page.locator('[data-field="theme.cardRadius"]').fill('22');await page.locator('[data-field="theme.font"]').selectOption('serif');await page.locator('[data-field="theme.mode"]').selectOption('black');assert.equal(await page.locator('#designThemePreview').evaluate(e=>getComputedStyle(e).backgroundColor),'rgb(23, 23, 23)');
 assert.equal(await page.locator('#designThemePreview').evaluate(x=>getComputedStyle(x).borderRadius),'22px');
 await page.locator('[data-act="save"]').click();await page.waitForFunction(()=>document.querySelector('.v5-dirty')?.hidden===true);
 assert.equal(saved.theme.mode,'black');assert.equal(saved.theme.accent,'#1266cc');assert.equal(saved.theme.font,'serif');assert.equal(saved.customProducts[0].id,'keep-product');
 await page.locator('.v5-design-links [data-nav="data"]').click();await page.getByRole('button',{name:'Simpan Semua Data Web ke CMS',exact:true}).click();await page.waitForFunction(()=>document.querySelector('.v5-dirty')?.hidden===true);
 assert.equal(saved.customProducts.filter(p=>p.id==='website-camera').length,1);assert.equal(saved.customProducts[0].id,'keep-product');assert.equal(saved.banners[0].title,'Sewa 3 Hari, Bayar 2 Hari');assert.ok(saved.media.some(m=>m.url===saved.banners[0].image));assert.equal(saved.appearance.heroSlides.length,3);assert.equal(saved.theme.accent,'#1266cc');
 await page.getByRole('button',{name:'Simpan Semua Data Web ke CMS',exact:true}).click();await page.waitForFunction(()=>document.querySelector('.v5-dirty')?.hidden===true);assert.equal(saved.customProducts.filter(p=>p.id==='website-camera').length,1);
 await page.locator('.v5-design-links [data-nav="products"]').click();await page.locator('[data-act="edit-product"][data-id="keep-product"]').click();
 await page.locator('[data-mf="name"]').fill('Live Camera Preview');await page.locator('[data-mf="price"]').fill('400000');await page.locator('[data-mf="discountPercent"]').fill('25');
 await page.locator('[data-mf="includedText"]').fill('Body kamera\nBaterai');await page.locator('[data-mf="accessoriesText"]').fill('Tripod');await page.locator('[data-mf="specText"]').fill('Sensor | Full frame');await page.locator('[data-mf="seoDescription"]').fill('Deskripsi SEO langsung');await page.locator('[data-mf="aeoAnswer"]').fill('Jawaban preview lengkap');await page.locator('[data-mf="geoSummary"]').fill('Ringkasan AI langsung');
 await page.locator('.cms-preview-data>summary').click();const fullPreview=page.locator('#cmsLiveProductPreview');for(const text of ['Body kamera','Baterai','Tripod','Full frame','Deskripsi SEO langsung','Jawaban preview lengkap','Ringkasan AI langsung','Publikasi & Penempatan','Label & Promo'])assert.ok((await fullPreview.textContent()).includes(text),text);
 assert.equal(await fullPreview.locator('[data-preview-photo]').count(),2);await fullPreview.locator('[data-preview-photo="1"]').click();assert.equal(await fullPreview.locator('.cms-preview-photo img').getAttribute('src'),'https://example.com/two.jpg');assert.equal(await fullPreview.locator('.cms-preview-info p').evaluate(e=>getComputedStyle(e).maxHeight),'none');
 assert.equal(await page.locator('#cmsLiveProductPreview h3').textContent(),'Live Camera Preview');assert.ok((await page.locator('#cmsLiveProductPreview strong').textContent()).includes('300.000'));
 for(const width of [1280,768,390]){await page.setViewportSize({width,height:900});assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth),width);assert.ok(await page.locator('#cmsLiveProductPreview').isVisible());}
 const websiteFrame=page.frameLocator('#cmsWebsiteProductPreview');await websiteFrame.getByRole('heading',{name:'Live Camera Preview',exact:true}).waitFor();
 await page.locator('[data-aeo-add]').click();await page.locator('[data-aeo-q="1"]').fill('Apa isi paket?');await page.locator('[data-aeo-a="1"]').fill('Body kamera dan baterai.');await page.locator('[data-aeo-q="0"]').fill('Bagaimana menyewa?');
 await websiteFrame.locator('.rc-product-faq details').nth(1).waitFor();assert.equal(await websiteFrame.locator('.rc-product-faq details').count(),2);assert.ok((await websiteFrame.locator('.rc-product-knowledge').allTextContents()).join(' ').includes('Ringkasan AI langsung'));
 await page.locator('[data-aeo-remove="1"]').click();await websiteFrame.locator('.rc-product-faq details').waitFor();assert.equal(await websiteFrame.locator('.rc-product-faq details').count(),1);
 await page.getByRole('button',{name:'Batal',exact:true}).click();assert.equal(saved.customProducts.find(p=>p.id==='keep-product').name,'Camera Fixture');
 await page.locator('[data-act="edit-product"][data-id="keep-product"]').click();await page.locator('[data-aeo-example]').click();assert.equal(await page.locator('.cms-aeo-item').count(),2);await page.locator('[data-geo-example]').click();assert.ok((await page.locator('[data-mf="geoSummary"]').inputValue()).includes('Camera Fixture'));await page.locator('[data-act="save-modal"]').click();await page.locator('[data-act="save"]').click();await page.waitForFunction(()=>document.querySelector('.v5-dirty')?.hidden===true);assert.equal(saved.customProducts.find(p=>p.id==='keep-product').aeoFaq.length,2);
 await page.locator('[data-act="edit-product"][data-id="keep-product"]').click();assert.equal(await page.locator('.cms-aeo-item').count(),2);await page.getByRole('button',{name:'Batal',exact:true}).click();
 await page.locator('[data-order-move="-1"][data-id="website-camera"]').click();assert.equal(await page.locator('.cms-order-item').first().getAttribute('data-order-id'),'website-camera');
 await page.locator('[data-act="save"]').click();await page.waitForFunction(()=>document.querySelector('.v5-dirty')?.hidden===true);assert.equal(saved.productOverrides['website-camera'].sortOrder,1);assert.equal(saved.productOverrides['keep-product'].sortOrder,2);
 await page.setViewportSize({width:1440,height:1000});
 await page.locator('.v5-design-links [data-nav="design-features"]').click();await page.locator('[data-field="theme.switchEnabled"]').uncheck();await page.locator('[data-act="save"]').click();await page.waitForTimeout(100);assert.equal(saved.theme.switchEnabled,false);await page.locator('[data-field="commerce.checkoutEnabled"]').uncheck();await page.locator('[data-field="commerce.trackingEnabled"]').uncheck();await page.locator('[data-field="general.marketingWhatsapp"]').fill('081234567890');await page.locator('[data-act="save"]').click();await page.waitForTimeout(100);assert.equal(saved.commerce.checkoutEnabled,false);assert.equal(saved.commerce.trackingEnabled,false);assert.equal(saved.general.marketingWhatsapp,'081234567890');await page.locator('.v5-design-links [data-nav="design-hero"]').click();await page.locator('[data-field="appearance.heroSlides.0.title"]').fill('Banner edited in CMS');await page.locator('[data-act="save"]').click();await page.waitForTimeout(100);
 await page.locator('.v5-design-links [data-nav="banners"]').click();assert.equal(await page.locator('[data-banner-preview]').count(),3);assert.equal(await page.locator('.v5-table .v5-prod img').count(),3);await page.locator('[data-act="edit-simple"][data-kind="banners"]').first().click();await page.locator('[data-mf="image"]').fill('https://example.com/catalog-edited.jpg');await page.locator('[data-mf="cta"]').fill('Promo baru');await page.locator('[data-act="save-modal"]').click();await page.locator('[data-act="save"]').click();await page.waitForTimeout(100);assert.equal(saved.banners[0].image,'https://example.com/catalog-edited.jpg');assert.equal(saved.banners[0].cta,'Promo baru');
 assert.equal(saved.appearance.heroSlides[0].title,'Banner edited in CMS');assert.ok(Array.isArray(saved.appearance.heroSlides));
 await page.locator('.v5-design-links [data-nav="design-nav"]').click();await page.locator('[data-design-add="navigation"]').click();await page.locator('[data-field="navigation.4.label"]').fill('Tentang Kami');await page.locator('[data-field="navigation.4.path"]').fill('/artikel');await page.locator('[data-act="save"]').click();await page.waitForTimeout(100);assert.equal(saved.navigation[4].label,'Tentang Kami');
 await page.locator('.v5-design-links [data-nav="footer"]').click();await page.locator('[data-design-add="footer.columns"]').click();await page.locator('[data-field="footer.columns.0.title"]').fill('Bantuan');await page.locator('[data-design-add="footer.columns.0.links"]').click();await page.locator('[data-field="footer.columns.0.links.0.label"]').fill('Hubungi Kami');await page.locator('[data-act="save"]').click();await page.waitForTimeout(100);assert.equal(saved.footer.columns[0].links[0].label,'Hubungi Kami');
 await page.reload();await page.locator('[data-field="theme.switchEnabled"]').waitFor();assert.equal(await page.locator('.v5-nav').evaluate(e=>e.firstElementChild.className),'v5-design-menu');assert.equal(await page.locator('.v5-design-menu summary').textContent(),'Pengaturan Web');await page.locator('.v5-design-links [data-nav="design-hero"]').click();assert.equal(await page.locator('[data-field="appearance.heroSlides.0.title"]').inputValue(),'Banner edited in CMS');
 await page.locator('.v5-design-links [data-nav="design-copy"]').click();await page.locator('[data-field="copy.catalogTitle"]').fill('Unsaved Title');failSave=true;await page.locator('[data-act="save"]').click();await page.locator('.v5-toast.bad').waitFor();assert.equal(await page.locator('.v5-dirty').isVisible(),true);assert.notEqual(saved.copy?.catalogTitle,'Unsaved Title');failSave=false;
 await page.setViewportSize({width:390,height:844});await page.getByRole('button',{name:'Buka menu',exact:true}).click();await page.locator('.v5-design-links [data-nav="design-theme"]').click();assert.equal(await page.locator('.v5').evaluate(x=>x.classList.contains('open')),false);assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth),390);
 await page.getByRole('button',{name:'Buka menu',exact:true}).click();await page.locator('.v5-side').evaluate(x=>x.scrollTop=x.scrollHeight);await page.screenshot({path:require('path').join(require('os').tmpdir(),'cms-workspace-mobile-menu.png')});
 await page.getByRole('button',{name:'Tutup menu',exact:true}).last().click();await page.locator('[data-act="cms-theme"]').click();await page.screenshot({path:require('path').join(require('os').tmpdir(),'cms-workspace-theme.png')});assert.deepEqual(errors,[]);console.log('CMS appearance tests passed: sidebar, mobile overflow, live preview, save, reload, footer/menu editing, product preservation, save failure. Writes:',writes);
 await browser.close();server.close();
})().catch(e=>{console.error(e);server.close();process.exit(1);});
