const {chromium}=require('playwright');const fs=require('fs'),http=require('http'),assert=require('assert');
const base=require('path').resolve(__dirname,'..');
const luminance=s=>s.match(/\d+/g).slice(0,3).map(Number).map(v=>v/255).map(v=>v<=.04045?v/12.92:((v+.055)/1.055)**2.4).reduce((a,v,i)=>a+v*[.2126,.7152,.0722][i],0);
const contrast=(a,b)=>{a=luminance(a);b=luminance(b);return (Math.max(a,b)+.05)/(Math.min(a,b)+.05)};
const fixture={general:{siteName:'Fixture Camera'},customProducts:[{id:'keep-product',name:'Camera Fixture',price:250000,stock:2,images:['https://example.com/one.jpg','https://example.com/two.jpg']}],appearance:{},footer:{description:'Original description',copyright:'Original copyright',columns:[]}};
let reviewRows=[{id:'test-review',name:'Pelanggan Uji',kind:'review',rating:4,message:'Layanan rental sangat baik.',published:false,created_at:'2026-10-02T00:00:00Z'},{id:'test-feedback',name:'Masukan Uji',kind:'feedback',message:'Tambahkan pilihan peralatan.',published:false,created_at:'2026-10-02T00:00:00Z'}];
let reviewSubmission=null;fixture.footer.contactPhone="085552372728";let saved=structuredClone(fixture),writes=0,failSave=false;
const server=http.createServer((req,res)=>{
 if(req.url.startsWith('/produk/')){res.setHeader('Content-Type','text/html');return res.end(`<html><head><link rel="stylesheet" href="/product-knowledge-20261002.css"></head><body><main id="app"></main><script>window.P=[];window.RENTCAM_CMS_CONFIG={};function render(){document.getElementById('app').innerHTML='<h1>'+String(P[0]?.name||'Product')+'</h1>'}</script><script src="/product-knowledge-20261002.js"></script><script src="/seo-runtime-20260930.js"></script><script src="/product-preview-20261002.js"></script></body></html>`);}
 if(req.url==='/cms'){res.setHeader('Content-Type','text/html');return res.end(`<!doctype html><html><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><link rel="stylesheet" href="/cms-v5-readable-20260912.css"><link rel="stylesheet" href="/cms-appearance-20260930.css"></head><body><main id="app"></main><script>localStorage.setItem('rentcam_cms_auth',JSON.stringify({access_token:'local-test-only'}));window.P=[{id:"website-camera",name:"Website Camera",brand:"Fixture Brand",cat:"Camera",price:100000,img:"https://example.com/camera.jpg"}];window.SL=[{id:"website-promo",t:"Website Promo",p:"Original promo",img:"https://example.com/banner.jpg"}];window.PORT=[];window.ART=[];</script><script src="/website-design-lib-20260930.js"></script><script src="/cms-config-store-20260918.js"></script><script src="/cms-publishing-20260918.js"></script><script src="/member-registration-config-20261003.js"></script><script src="/link-page-config-20261003.js"></script><script src="/cms-admin-all-tables-adapter-20260918.js"></script><script src="/cms-ui-final-20260918.js"></script><script src="/cms-template-publishing-adapter-20260918.js"></script></body></html>`);}
 const file=base+req.url.split('?')[0];if(!file.startsWith(base+'/')||req.url.includes('..')){res.statusCode=404;return res.end();}
 try{res.setHeader('Content-Type',req.url.split('?')[0].endsWith('.css')?'text/css':req.url.endsWith('.html')?'text/html':'application/javascript');res.end(fs.readFileSync(file));}catch(_){res.statusCode=404;res.end();}
});
(async()=>{
 await new Promise(r=>server.listen(0,'127.0.0.1',r));const url='http://127.0.0.1:'+server.address().port+'/cms';
 const browser=await chromium.launch({headless:true,executablePath:'/usr/bin/chromium',args:['--no-sandbox']});
 const context=await browser.newContext();
 await context.route('https://xleceiffuopioeguniwj.supabase.co/**',async route=>{
  const req=route.request();if(req.url().includes('/rest/v1/rentcam_reviews')){if(req.method()==='POST'){reviewSubmission=JSON.parse(req.postData());return route.fulfill({status:204})}if(req.method()==='PATCH'){reviewRows[0].published=JSON.parse(req.postData()).published;return route.fulfill({status:204})}return route.fulfill({contentType:'application/json',body:JSON.stringify(reviewRows)})}if(req.url().includes('/rest/v1/rentcam_order_catalog'))return route.fulfill({contentType:'application/json',body:'[]'});if(!req.url().includes('/rest/v1/rentcam_cms_config'))throw Error('Unexpected network request: '+req.url());
  if(req.method()==='PATCH'){if(failSave)return route.fulfill({status:500,contentType:'application/json',body:JSON.stringify({message:'Fixture save error'})});saved=JSON.parse(req.postData()).config;writes++;return route.fulfill({status:204});}
  return route.fulfill({contentType:'application/json',body:JSON.stringify([{config:saved}])});
 });
 const page=await context.newPage();const errors=[];page.on('pageerror',e=>errors.push(e.message));
 await page.goto(url);await page.locator('[data-field="theme.switchEnabled"]').waitFor();assert.equal(await page.locator('.v5-nav').evaluate(e=>e.firstElementChild.className),'v5-design-menu');assert.equal(await page.locator('.v5-design-menu summary').textContent(),'Pengaturan Web');
 assert.equal(await page.locator('.v5-design-menu').count(),1);assert.equal(await page.locator('.v5-design-menu [data-tpl-nav]').count(),1);
 await page.locator('[data-nav=reviews]').click();await page.locator('[data-review-publish]').waitFor();assert.equal(await page.locator('[data-review-publish]').count(),1);await page.locator('[data-review-publish]').click();await page.getByRole('button',{name:'Sembunyikan',exact:true}).waitFor();assert.equal(reviewRows[0].published,true);await page.getByRole('button',{name:'Sembunyikan',exact:true}).click();await page.getByRole('button',{name:'Tampilkan di Website',exact:true}).waitFor();assert.equal(reviewRows[0].published,false);await page.locator('[data-nav=design-features]').click();

 await page.locator('[data-nav=design-links]').first().click();await page.locator('[data-field="linkPage.title"]').fill('Rentalall Studio');await page.locator('[data-field="linkPage.subtitle"]').fill('Semua kebutuhan produksi Anda');await page.locator('[data-field="linkPage.links.4.enabled"]').uncheck();await page.locator('[data-link-add]').click();await page.locator('[data-field="linkPage.links.7.label"]').fill('Portfolio Rentalall');await page.locator('[data-field="linkPage.links.7.url"]').fill('/portfolio');await page.locator('[data-act=save]').click();await page.waitForFunction(()=>document.querySelector('.v5-dirty')?.hidden===true);assert.equal(saved.linkPage.links.length,8);await page.reload();await page.locator('[data-nav=design-links]').first().click();assert.equal(await page.locator('[data-field="linkPage.title"]').inputValue(),'Rentalall Studio');
 await page.goto(url.replace('/cms','/links.html'));await page.getByRole('heading',{name:'Rentalall Studio',exact:true}).waitFor();assert.equal(await page.locator('.rc-link-card').count(),7);assert.equal(await page.locator('.rc-link-card[data-action=whatsapp]').getAttribute('href'),'https://wa.me/6285552372728');assert.equal(await page.getByRole('link',{name:/Instagram/}).count(),0);assert.equal(await page.getByRole('link',{name:/Portfolio Rentalall/}).getAttribute('href'),'/portfolio');for(const width of [320,390,1024]){await page.setViewportSize({width,height:900});assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth),width);}await page.setViewportSize({width:390,height:844});await page.screenshot({path:'/tmp/link-page-mobile.png',fullPage:true});
 await page.locator('[data-register-member]').click();await page.locator('#rcMemberDialog').waitFor();assert.equal(await page.locator('.rc-member-summary').count(),0);await page.locator('[data-member-close]').click();await page.locator('[data-customer-reviews]').click();await page.locator('#rcReviewDialog').waitFor();assert.equal(await page.getByText('Kiriman masuk ke CMS. Admin menentukan apakah ulasan ditampilkan di website.',{exact:true}).count(),0);await page.locator('#rcReviewDialog [name=name]').fill('Pelanggan Uji');await page.getByRole('radio',{name:'5 bintang',exact:true}).check();assert.equal(await page.locator('.rc-review-stars [data-active=true]').count(),5);await page.locator('#rcReviewDialog [name=message]').fill('Peralatan lengkap dan pelayanan sangat baik.');await page.screenshot({path:'/tmp/review-form-mobile.png'});await page.locator('#rcReviewDialog [type=submit]').click();await page.waitForFunction(()=>document.querySelector('[data-review-status]').textContent.includes('berhasil'));assert.equal(reviewSubmission.rating,5);assert.equal(reviewSubmission.published,false);assert.equal(await page.locator('.rc-review-stars [data-active=true]').count(),0);
 await page.locator('#rcReviewDialog [name=kind]').selectOption('feedback');assert.equal(await page.locator('.rc-review-stars').isVisible(),false);await page.locator('#rcReviewDialog [name=name]').fill('Masukan Uji');await page.locator('#rcReviewDialog [name=message]').fill('Tambahkan lebih banyak pilihan lensa.');await page.locator('#rcReviewDialog [type=submit]').click();await page.waitForFunction(()=>document.querySelector('[data-review-status]').textContent.includes('berhasil'));assert.equal(reviewSubmission.kind,'feedback');assert.equal(reviewSubmission.rating,null);for(const width of [320,390,1024]){await page.setViewportSize({width,height:844});assert(await page.locator('#rcReviewDialog').evaluate(el=>el.scrollWidth<=el.clientWidth));}await page.setViewportSize({width:1024,height:900});await page.screenshot({path:'/tmp/review-form-desktop.png'});await page.locator('[data-review-close]').click();await page.locator('#rcReviewDialog').waitFor({state:'detached'});assert.equal(await page.locator('#rcReviewDialog').count(),0);console.log('PASS: CMS link settings save/reload, add/hide links, public links, WhatsApp, member/review modals, rating, feedback, reset, mobile layout');await browser.close();server.close();
})().catch(e=>{console.error(e);server.close();process.exit(1)});
